name: Deploy my Front-End AWS Infrastructure
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo main branch
        uses: actions/checkout@v2
        
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Initializing Terraform
        run: terraform init
        working-directory: ./
        
      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./


