name: "Deploying infrastructure in AWS"

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Terraform"
    runs-on: ubuntu-latest
    outputs:
      cf_distribution_id: ${{ steps.sets-a-secret.outputs.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: 1.4.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Generate and Output a Secret
        id: sets-a-secret
        run: |
          CF_ID=`terraform output -raw cloudfront_distribution_id`
          echo "CLOUDFRONT_DISTRIBUTION_ID=$CF_ID" >> $GITHUB_OUTPUT

      #- name: Use that secret output (protected by a mask)
      #  run: |
      #  echo "the secret number is ${{ steps.sets-a-secret.outputs.CLOUDFRONT_DISTRIBUTION_ID }}"


  upload:
    name: "Upload HTML Files"
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: S3/CloudFront Deploy
        uses: staevs/s3-deploy-action@v1.2.2
        if: success()
        with:
          args: --follow-symlinks --delete --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ needs.deploy.outputs.cf_distribution_id }}
          S3_SOURCE_DIR: './webfiles'
